// Code generated by protoc-gen-go.
// source: github.com/micro/explorer-srv/proto/organization/organization.proto
// DO NOT EDIT!

/*
Package organization is a generated protocol buffer package.

It is generated from these files:
	github.com/micro/explorer-srv/proto/organization/organization.proto

It has these top-level messages:
	Organization
	Member
	CreateRequest
	CreateResponse
	DeleteRequest
	DeleteResponse
	ReadRequest
	ReadResponse
	UpdateRequest
	UpdateResponse
	SearchRequest
	SearchResponse
	CreateMemberRequest
	CreateMemberResponse
	DeleteMemberRequest
	DeleteMemberResponse
	ReadMemberRequest
	ReadMemberResponse
	UpdateMemberRequest
	UpdateMemberResponse
	SearchMembersRequest
	SearchMembersResponse
*/
package organization

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type Organization struct {
	Id      string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Email   string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Owner   string `protobuf:"bytes,4,opt,name=owner" json:"owner,omitempty"`
	Created int64  `protobuf:"varint,5,opt,name=created" json:"created,omitempty"`
	Updated int64  `protobuf:"varint,6,opt,name=updated" json:"updated,omitempty"`
}

func (m *Organization) Reset()         { *m = Organization{} }
func (m *Organization) String() string { return proto.CompactTextString(m) }
func (*Organization) ProtoMessage()    {}

type Member struct {
	Id       string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	OrgName  string   `protobuf:"bytes,2,opt,name=orgName" json:"orgName,omitempty"`
	Username string   `protobuf:"bytes,3,opt,name=username" json:"username,omitempty"`
	Roles    []string `protobuf:"bytes,4,rep,name=roles" json:"roles,omitempty"`
	Created  int64    `protobuf:"varint,5,opt,name=created" json:"created,omitempty"`
	Updated  int64    `protobuf:"varint,6,opt,name=updated" json:"updated,omitempty"`
}

func (m *Member) Reset()         { *m = Member{} }
func (m *Member) String() string { return proto.CompactTextString(m) }
func (*Member) ProtoMessage()    {}

type CreateRequest struct {
	Organization *Organization `protobuf:"bytes,1,opt,name=organization" json:"organization,omitempty"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}

func (m *CreateRequest) GetOrganization() *Organization {
	if m != nil {
		return m.Organization
	}
	return nil
}

type CreateResponse struct {
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}

type DeleteRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}

type DeleteResponse struct {
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}

type ReadRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *ReadRequest) Reset()         { *m = ReadRequest{} }
func (m *ReadRequest) String() string { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()    {}

type ReadResponse struct {
	Organization *Organization `protobuf:"bytes,1,opt,name=organization" json:"organization,omitempty"`
}

func (m *ReadResponse) Reset()         { *m = ReadResponse{} }
func (m *ReadResponse) String() string { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()    {}

func (m *ReadResponse) GetOrganization() *Organization {
	if m != nil {
		return m.Organization
	}
	return nil
}

type UpdateRequest struct {
	Organization *Organization `protobuf:"bytes,1,opt,name=organization" json:"organization,omitempty"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}

func (m *UpdateRequest) GetOrganization() *Organization {
	if m != nil {
		return m.Organization
	}
	return nil
}

type UpdateResponse struct {
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}

type SearchRequest struct {
	Name   string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Owner  string `protobuf:"bytes,2,opt,name=owner" json:"owner,omitempty"`
	Limit  int64  `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
	Offset int64  `protobuf:"varint,4,opt,name=offset" json:"offset,omitempty"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}

type SearchResponse struct {
	Organizations []*Organization `protobuf:"bytes,1,rep,name=organizations" json:"organizations,omitempty"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}

func (m *SearchResponse) GetOrganizations() []*Organization {
	if m != nil {
		return m.Organizations
	}
	return nil
}

type CreateMemberRequest struct {
	Member *Member `protobuf:"bytes,1,opt,name=member" json:"member,omitempty"`
}

func (m *CreateMemberRequest) Reset()         { *m = CreateMemberRequest{} }
func (m *CreateMemberRequest) String() string { return proto.CompactTextString(m) }
func (*CreateMemberRequest) ProtoMessage()    {}

func (m *CreateMemberRequest) GetMember() *Member {
	if m != nil {
		return m.Member
	}
	return nil
}

type CreateMemberResponse struct {
}

func (m *CreateMemberResponse) Reset()         { *m = CreateMemberResponse{} }
func (m *CreateMemberResponse) String() string { return proto.CompactTextString(m) }
func (*CreateMemberResponse) ProtoMessage()    {}

type DeleteMemberRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteMemberRequest) Reset()         { *m = DeleteMemberRequest{} }
func (m *DeleteMemberRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteMemberRequest) ProtoMessage()    {}

type DeleteMemberResponse struct {
}

func (m *DeleteMemberResponse) Reset()         { *m = DeleteMemberResponse{} }
func (m *DeleteMemberResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteMemberResponse) ProtoMessage()    {}

type ReadMemberRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *ReadMemberRequest) Reset()         { *m = ReadMemberRequest{} }
func (m *ReadMemberRequest) String() string { return proto.CompactTextString(m) }
func (*ReadMemberRequest) ProtoMessage()    {}

type ReadMemberResponse struct {
	Member *Member `protobuf:"bytes,1,opt,name=member" json:"member,omitempty"`
}

func (m *ReadMemberResponse) Reset()         { *m = ReadMemberResponse{} }
func (m *ReadMemberResponse) String() string { return proto.CompactTextString(m) }
func (*ReadMemberResponse) ProtoMessage()    {}

func (m *ReadMemberResponse) GetMember() *Member {
	if m != nil {
		return m.Member
	}
	return nil
}

type UpdateMemberRequest struct {
	Member *Member `protobuf:"bytes,1,opt,name=member" json:"member,omitempty"`
}

func (m *UpdateMemberRequest) Reset()         { *m = UpdateMemberRequest{} }
func (m *UpdateMemberRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateMemberRequest) ProtoMessage()    {}

func (m *UpdateMemberRequest) GetMember() *Member {
	if m != nil {
		return m.Member
	}
	return nil
}

type UpdateMemberResponse struct {
}

func (m *UpdateMemberResponse) Reset()         { *m = UpdateMemberResponse{} }
func (m *UpdateMemberResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateMemberResponse) ProtoMessage()    {}

type SearchMembersRequest struct {
	OrgName  string `protobuf:"bytes,1,opt,name=orgName" json:"orgName,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Limit    int64  `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
	Offset   int64  `protobuf:"varint,4,opt,name=offset" json:"offset,omitempty"`
}

func (m *SearchMembersRequest) Reset()         { *m = SearchMembersRequest{} }
func (m *SearchMembersRequest) String() string { return proto.CompactTextString(m) }
func (*SearchMembersRequest) ProtoMessage()    {}

type SearchMembersResponse struct {
	Members []*Member `protobuf:"bytes,1,rep,name=members" json:"members,omitempty"`
}

func (m *SearchMembersResponse) Reset()         { *m = SearchMembersResponse{} }
func (m *SearchMembersResponse) String() string { return proto.CompactTextString(m) }
func (*SearchMembersResponse) ProtoMessage()    {}

func (m *SearchMembersResponse) GetMembers() []*Member {
	if m != nil {
		return m.Members
	}
	return nil
}

func init() {
}
